--- 
- hosts: all 
  become: yes
  tasks: 
  - name: install webservers 
    apt:
      name: apache2
      state: present 
  - name: install tree 
    apt: 
      name: tree 
      state: present 
      