---
- name: download tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
    force_basic_auth: yes

- name: extract tar file 
  command: 
      cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
      creates: /opt/tomcat/LICENSE
      