---
- name: remove tomcat user
  user:
    name: tomcat
    state: 	absent
- name: create user 
  command: sudo useradd -m -d /opt/tomcat -U -s /bin/false tomcat

- name: update package
  apt:
     update_cache: yes

- name: install java8
  apt:
    name: openjdk-8-jre
    state: present

